### ISSUE TITLE
Add the necessary #require directives where appropriate

### ISSUE THREAD

**Issue by shindere** [Sudha247/ocaml5-tutorial-icfp-22#2]
So that the `open domainslib` directives work.

**Comment by Leonidas-from-XIV** [comment]
In the case of the slides we didn't want to clutter them, in the case of the code we the libraries are loaded via `dune`? Maybe we should instead note to use `dune utop` instead of plain `utop`, e.g. in the README? I just tested it and `open Domainslib;;` works with `dune utop`.
